### Mission 

- extraire la 3é colonn du dataset et le comarare au pays "canada", assigner le résultat à la variable counttrie_variable
- Extraire la 1er colonne du dataset et comaprer la chaine de caractéres  "1984". Assigner le résultat à la variable years 1984

In [1]:
import numpy as np

In [64]:
world_alcool = np.genfromtxt('original.csv', delimiter= ",", dtype= "U75", skip_header=1)
print(world_alcool)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [4]:
contries_canada= (world_alcool[:,2] == "Canada")

In [7]:
years_1984 = (world_alcool[:,0] == "1984")

array([False, False, False, ..., False, False, False])

### Selectionner des elements

In [9]:
vector = np.array([5, 10, 15,20])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[10]


In [17]:
matrix = np.array([[5, 10, 15], [20, 25 , 30], [35, 40, 45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [19]:
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25, :])

[[20 25 30]]


- Comparer la 3e colonne du data set à la chaine de caractére "Algeria"
- Assigner le résultat à la variable country_is_algeria
- Sélectionner seulement les lignes du dataset pour lesquelles country_is_algeria vaut True
- Assigner le résultat à la variable country_algéria
- Afficher les résultats
- Faire le même travail pour récupérer toutes les lignes corrrspondantes à l'année "1984". Assigner les résultat à la variable years_1984

In [20]:
country_is_algeria = world_alcool[:,2] =="Algeria"
country_algeria = world_alcool[country_is_algeria]
print(country_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [22]:
years_is_1984 = world_alcool[:,0] == "1984"
years_1984 = world_alcool[years_is_1984]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [26]:
# sur une ligne
years_1986 = world_alcool[world_alcool[:,0] == "1986"]
print(years_1986)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['1986' 'Western Pacific' 'Fiji' 'Spirits' '0.05']
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


### Effectuer des comparaisons avec plusieur conditions

In [30]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [32]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


- Sélectionner les lignes dont le pays est "Algéria" et l'année "1986"
 - Créer cette double comparaison et assigner le résultat à la variable is_algeria_and_1986
 - Utiliser is_algeria_and_1986 pour selectionner les ligne correpondantes dans le data set
 - Assigner le résultat à la variable rows_with_algeria_and_1986
 - afficher le résulat


In [36]:
is_algeria_and_1986 = (world_alcool[:,2] == "Algeria") & (world_alcool[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcool[is_algeria_and_1986]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


### Remplacer des valeur dans un tableau Numpy

In [37]:
vector

array([ 5, 10, 15, 20])

In [38]:
print(equal_to_ten_or_five) 

[ True  True False False]


In [39]:
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [40]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
second_column_25 = matrix[:, 1] == 25
matrix[second_column_25, 1] = 10
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


### Remplacer des valeurs dans un tableau Numpy
- Créer un tableau numpy world_alcool_2 égal worl_alcool
- Remplacer toutes les années "1986" de la 1er colonne de world alcool_2 par "2018"
- Remplacer tous les aclool "Wine" de la 4éme colonne par "Beer"

In [47]:
world_alcool_2 = world_alcool
world_alcool_2[:, 0][world_alcool_2[:, 0] == "1986"] = "2018"
world_alcool_2[:, 3][world_alcool_2[:, 3] == "Wine"] = "Beer"
print(world_alcool_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


### Remplacer les chaines de caractére vides
- Comparer les tous les éléments de la 5é colonne du dataset avec la chaine de caractéres vide c'est à dire"". Assigner le résultat à la variable is_value_empty
- Sélectionner toute les valeurs de la 5e colonnes du data pour lesquelles is_value_empty est égal à True et enfin les rempalcer par la chaine de caractére '0'

In [48]:
is_value_empty = world_alcool[:,4]==""
world_alcool[is_value_empty, 4] = 0

### Convertir des types de donéées

In [50]:
# astype()
vector1 = np.array(["1", "2", "3"])
vector1 = vector1.astype(float)
vector1

array([1., 2., 3.])

### Convertir des types de données
- Extraire la 5é colonne de world_alcool et assiger le résulat à la variable alcool_consumption
- Utiliser la méthode astype() pour convertir alcool_consumption en décimal(float)

In [52]:
alcool_consumption = world_alcool[:, 4]
alcool_consumption = alcool_consumption.astype(float)
print(alcool_consumption)

[0.   0.5  1.62 ... 2.54 0.   5.15]


### Réaliser des calculs mathématiques avec Numpy

In [53]:
# sum()
# mean()
# max()

In [58]:
print(vector)
vector.sum()

[50 50 15 20]


135

In [55]:
vector.mean()

33.75

In [56]:
vector.max()

50

In [59]:
# matrix axis 1 ligne, 0 colonne
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [60]:
matrix.sum(axis = 1)

array([ 30,  60, 120])

In [61]:
matrix.sum(axis = 0)

array([60, 60, 90])

### Réaliser des calculs mathématiques avec Numpy
- Utiliser la méthode sum() pour calculer la somme de alcool_consumption. Assigner le résultat à la variable total_alcool
- Utiliser la méthode mean() pour calculer la somme de alcool_consumption. Assigner le résultat à la variable average_alcool
- Afficher les résultats

In [62]:
total_alcool = alcool_consumption.sum()
print(total_alcool)

3908.96


In [63]:
average_alcool = alcool_consumption.mean()
print(average_alcool)

1.2001719373656738


### Calculer la consommation totale annuelle par habitant pour un pays donné
- Créer une matrice qu'on nommera canada_1986 qui contient toutes les lignes du dataset correspondant à l'année "1986" et au pays "canada"
- Extraire la 5eme colonne de canada_1986, remplacer tout chaine de caractéres("") par "0"et convertir la colonne en décimal(float). Assigner le résultat à la variable canada_alcool
- Calculer la somme de canada_alcool. Assigner le résultat
- Afficher

In [68]:
is_canada_1986 = (world_alcool[:,0] == "1986") & (world_alcool[:,2] == "Canada")
canada_1986 = world_alcool[is_canada_1986]
print(canada_1986)


[['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]


In [82]:
canada_alcool = canada_1986[:,4]
empty_value = canada_alcool == ""
canada_alcool[empty_value] = 0
print(canada_alcool)

['0' '3.11' '4.87' '1.33']


In [87]:
canada_alcool = canada_alcool.astype(float)
print(canada_alcool)
total_alcool = canada_alcool.sum()
print(total_alcool)

[0.   3.11 4.87 1.33]
9.31


### Calculer la consomation pour chaque pays
- Tout d'abord, on crée un dico vide qui va contenir tous les pays et leurs consommations d'alcool associées, on le nommera totals
- Selectionner ensuite les lignes du dataset correspondant a l'année 1989, Assigner le résultat à la variable year
- Selectionner dans une liste qu'on nommera countries tout les pays
- Parcourir tous les pays de la lsites à l'aide d'une boucle.
- Pour chaque pays:
    - Sélectionner les lignes de Year correspondant à ce pays 
    - Assigner le résultat à la variable country_conso
    - Extraire la 5éme colonne de country_conso
    - Remplacer toute chaine de caractére vide par 0
    - Convertir colonne en décimal(float)
    - Calculer la somme de la colonne
    - ajouter la somme au dico totals, avec comme clé le nom du pays et en valeur la somme
- Afficher le dico total

In [106]:
totals = {}

is_year = world_alcool[:,0] == "1989"
year = world_alcool[is_year,:]
countries = world_alcool[:,2]

for country in countries:
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = round(alcohol_column.sum(),2)
    
print(totals)

{'Viet Nam': 0.16, 'Uruguay': 7.44, "Cte d'Ivoire": 2.2, 'Colombia': 6.96, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.4, 'Seychelles': 3.3, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.11, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.9, 'Sierra Leone': 4.38, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42, 'Sweden': 7.47, 'Qatar': 1.45, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.01, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92, 'Trinidad and Tobago': 4.68, 'Mexico': 5.1, 'Nicaragua': 2.5, 'Malta': 7.13, 'Switzerland': 13.85, 'Finland': 9.42, 'Saudi Arabia': 0.15, 'Kuwait': 0.0, 'E

### Trouver le pays qui consomme le plus d'alcool
- Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
- Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
- Parcourir chaque pays du dictionnaire totals:
>- Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable highest_value et assigner la clé correspondante (nom du pays) à la variable highest_key.
- Afficher le pays qui consomme le plus d'alcool (variable highest_key)


In [127]:
highest_value = 0
highest_key = None

for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country
        
print("le pays qui consomme le plus d'alcool pour l'année 1989 est", highest_key , "avec une conso de :", highest_value , "Litres")

le pays qui consomme le plus d'alcool pour l'année 1989 est Hungary avec une conso de : 16.29 Litres
