Les tableaux avec Numpy


In [1]:
import numpy as np

vector = np.array([3, 4, 17, 65])


In [2]:
print(vector)

[ 3  4 17 65]


In [3]:
matrix = np.array([[2, 5, 15],[20,50,30], [34, 99, 45]])

In [4]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


ndarray.shape pour la taille d'un vecteur ou de la matrice

In [5]:
print(vector.shape)

(4,)


In [6]:
print(matrix.shape)

(3, 3)


### Fonction numpy pour lire un dataset: numpy.genfromtxt()
skip_header = 1 pour enlever l'entete à l'import du csv

In [7]:
world_alcool = np.genfromtxt("original.csv", delimiter =",", dtype="U75", skip_header = 1)

In [8]:
print(type(world_alcool))

<class 'numpy.ndarray'>


In [9]:
print(world_alcool)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [10]:
world_alcool.dtype

dtype('<U75')

In [11]:
print(world_alcool.dtype)

<U75


In [12]:
ivoire_1985 = world_alcool[2,4]
print(ivoire_1985)

1.62


In [13]:
second_country = world_alcool[1,2]
print(second_country)

Uruguay


### Extraire un vecteur d valeurs depuis un tableau numpy

In [14]:
vector[0:3]

array([ 3,  4, 17])

In [15]:
matrix

array([[ 2,  5, 15],
       [20, 50, 30],
       [34, 99, 45]])

In [16]:
matrix[:,1]

array([ 5, 50, 99])

In [19]:
matrix[2,:]

array([34, 99, 45])

In [20]:
matrix[1:3,1]

array([50, 99])

In [26]:
variable_country = world_alcool[:,2]
print(variable_country)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [29]:
variable_alcool_consumption = world_alcool[:,4]
print(variable_alcool_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


### Extraire un tableau de valeurs depuis une tableau Numpy

In [30]:
matrix[:,0:2]

array([[ 2,  5],
       [20, 50],
       [34, 99]])

In [31]:
matrix[1:3,:]

array([[20, 50, 30],
       [34, 99, 45]])

In [32]:
matrix[1:3,0:2]

array([[20, 50],
       [34, 99]])

In [34]:
first_two_columns = world_alcool[:,0:2]
first_two_columns

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ...,
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], dtype='<U75')

In [40]:
first_ten_years = world_alcool[0:10,0:1]
first_ten_years

array([['1986'],
       ['1986'],
       ['1985'],
       ['1986'],
       ['1987'],
       ['1987'],
       ['1987'],
       ['1985'],
       ['1986'],
       ['1984']], dtype='<U75')

In [41]:
first_ten_rows = world_alcool[0:10,:]
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75')

In [42]:
first_twenty_regions = world_alcool[0:20,1:3]
first_twenty_regions

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], dtype='<U75')